###########################################################
##                                                       ##
##              ordering width information               ##
##              **************************               ##
##                                                       ##
##      Authors: Pierre Artoisenet (UCL-CP3)             ##
##               Olivier Mattelaer (UCL-CP3)             ##
##                                                       ##
###########################################################
##    file generated automatically                       ##
## all_delta
###########################################################
## TAG         VALUE
  THIN         
  LARGE        
  X            0
  THETA        
  PHI          