#ifndef W4JETSINTEGRATIONMASK_HH_
#define W4JETSINTEGRATIONMASK_HH_

enum W4JetsIntegrationMask {
    I_PRIOR_DENSITY_MASK = 0x1,
    I_TF_MASK = 0x2,
    I_EFF_MASK = 0x4,
    I_ME_MASK = 0x8,
    I_JACOBIAN_MASK = 0x10
};

#endif // W4JETSINTEGRATIONMASK_HH_
