      DOUBLE PRECISION FUNCTION P1_DSIG(PP,WGT)
C     ****************************************************
C     
C     Generated by MadGraph5_aMC@NLO v. 2.2.2, 2014-11-06
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Process: g g > w- g g u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- g g c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- u u u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- c c c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- u c u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- c u c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- s u s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- b u b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- d c d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- b c b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- u d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g g > w- c s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u > w- g u u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c > w- g c c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u > w- g u c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c > w- g c u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d > w- g d c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s > w- g s u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d > w- g g g u WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s > w- g g g c WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d > w- g u u u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s > w- g c c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d > w- g u c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d > w- g u s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d > w- g u b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s > w- g c u u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s > w- g c d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s > w- g c b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d > w- g u d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s > w- g c s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u~ > w- g g g d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c~ > w- g g g s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u~ > w- g u u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c~ > w- g c c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u~ > w- g c u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c~ > w- g u c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d~ > w- g c d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s~ > w- g u s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u~ > w- g c c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u~ > w- g s s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u~ > w- g b b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c~ > w- g u u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c~ > w- g d d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c~ > w- g b b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g u~ > w- g d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g c~ > w- g s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g d~ > w- g u d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: g s~ > w- g c s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u > w- u u u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c > w- c c c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u > w- u u c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c > w- c u c d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d > w- d c d s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s > w- s u s d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c > w- u u c d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s > w- u u s d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d > w- c c d s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c > w- u c c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d > w- g g u u WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s > w- g g c c WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d > w- u u u u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s > w- c c c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d > w- u u c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d > w- u u s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d > w- u u b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s > w- c u c u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s > w- c c d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s > w- c c b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d > w- u u d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s > w- c c s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d > w- u c d s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s > w- c u s d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s > w- g g u c WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d > w- g g c u WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- g g d c WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s > w- u u c u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d > w- c u c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- d c d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s > w- u c c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d > w- u c u u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- c d c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s > w- u c d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s > w- u c b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d > w- c u s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d > w- c u b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- d c u u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- d c b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s > w- u c s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d > w- c u d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- d c s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- g g u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- g g c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- g g c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- g g u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- g g c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- g g u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- u u u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- c c c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- u c u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- c u c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- d c d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- s u s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- u c c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- u s s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- u b b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- c u u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- c d d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- c b b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- u d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- c s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- c c c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- u u u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- c c c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- u u u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- c d d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- c b b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- u s s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- u b b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- c u u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- c b b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- u c c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- u b b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u u~ > w- c s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c c~ > w- u d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- c s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- u d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c~ > w- g g u s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c u~ > w- g g c d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- g g d s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- g g s d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c~ > w- u u u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c u~ > w- c c c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- d d d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- s s s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c~ > w- u u c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s~ > w- u u s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c u~ > w- c c u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d~ > w- c c d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c~ > w- u c c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c u~ > w- c u u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- d c c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- s u u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c~ > w- u d d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c~ > w- u b b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c u~ > w- c s s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c u~ > w- c b b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- d u u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- d b b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- s c c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- s b b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u c~ > w- u s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c u~ > w- c d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- d s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- s d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d~ > w- u u d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s~ > w- c c s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u d~ > w- u c d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c s~ > w- c u s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- d c u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- s u c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u s~ > w- u c s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c d~ > w- c u d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s~ > w- d c s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s d~ > w- s u d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d > w- g g u d WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s > w- g g c s WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d > w- u u d u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s > w- c c s c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d > w- u c d c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d > w- u s d s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d > w- u b d b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s > w- c u s u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s > w- c d s d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s > w- c b s b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d > w- u d d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s > w- c s s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- g g u s WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- u u s u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- u c s c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- u b s b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- u d s d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s > w- u s s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- g g g g WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- g g g g WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- g g u u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- g g c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- g g c c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- g g s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- g g b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- g g u u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- g g d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- g g b b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- g g d d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- g g s s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- u u u~ u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- c c c~ c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- u c u~ c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- c d c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- u d u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- c s c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- u s u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- u b u~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- c b c~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- c c c~ c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- s s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- b b b~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- u u u~ u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- d d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- b b b~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- c d c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- u s u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- d s d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- c s c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- c b c~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- s b s~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- u b u~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- d b d~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- d d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- s s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- d s d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d u~ > w- d b d~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- s b s~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- g g u c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s~ > w- g g u s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- g g c u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s d~ > w- g g c d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- u u u~ c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s~ > w- u u u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- c c c~ u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s d~ > w- c c c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- u c c~ c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s~ > w- u s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- c u u~ u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s d~ > w- c d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- u d c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s~ > w- u d s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- c s u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s d~ > w- c s d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- u s c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d c~ > w- u b c~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s~ > w- u c s~ c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d s~ > w- u b s~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- c d u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s u~ > w- c b u~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s d~ > w- c u d~ u~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s d~ > w- c b d~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- g g u d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- g g c s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- u u u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- c c c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- u c c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- u s s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- u b b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- c u u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- c d d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- c b b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d d~ > w- u d d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s s~ > w- c s s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- u c u~ c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s c~ > w- u d u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ u~ > w- g g u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ c~ > w- g g c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ u~ > w- u u~ u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ c~ > w- c c~ c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ u~ > w- c u~ u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ c~ > w- u c~ c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d~ d~ > w- c d~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s~ s~ > w- u s~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ u~ > w- c u~ c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ u~ > w- s u~ s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ u~ > w- b u~ b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ c~ > w- u c~ u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ c~ > w- d c~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ c~ > w- b c~ b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ u~ > w- d u~ d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ c~ > w- s c~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- g g u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- g g c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ s~ > w- g g s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ d~ > w- g g d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- u u~ u~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- u u~ c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ s~ > w- u u~ s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ d~ > w- c c~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- c u~ c~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- c c~ c~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ s~ > w- s s~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ d~ > w- d d~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- d u~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- b u~ b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- d c~ d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ s~ > w- d d~ s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ d~ > w- s d~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- s u~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- s c~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ c~ > w- b c~ d~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ s~ > w- c s~ d~ c~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ s~ > w- b s~ d~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ d~ > w- u s~ u~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ d~ > w- b d~ s~ b~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ d~ > w- g g d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ s~ > w- g g s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ d~ > w- u u~ d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ s~ > w- c c~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ d~ > w- c u~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ s~ > w- u c~ s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ d~ > w- c c~ d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ d~ > w- s d~ s~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ d~ > w- b d~ b~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ s~ > w- u u~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ s~ > w- d d~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ s~ > w- b s~ b~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ d~ > w- d d~ d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ s~ > w- s s~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: u~ s~ > w- c u~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: c~ d~ > w- u c~ d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d~ s~ > w- c d~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d~ d~ > w- u d~ d~ d~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: s~ s~ > w- c s~ s~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     Process: d~ s~ > w- u d~ d~ s~ WEIGHTED=6 @1
C     *   Decay: w- > e- ve~ WEIGHTED=2
C     
C     RETURNS DIFFERENTIAL CROSS SECTION 
C     FOR MULTIPLE PROCESSES IN PROCESS GROUP
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     Output:
C     Amplitude squared and summed
C     ****************************************************
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      REAL*8     PI
      PARAMETER (PI=3.1415926D0)
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,K,ICONF,IMIRROR,NPROC
      SAVE NPROC
      LOGICAL MIRRORPROCS(MAXSPROC)
      INCLUDE 'mirrorprocs.inc'
      DOUBLE PRECISION XDUM
C     
C     EXTERNAL FUNCTIONS
C     
      DOUBLE PRECISION P1_DSIGPROC
      EXTERNAL P1_DSIGPROC
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
C     IPROC has the present process number
      INTEGER IPROC
      COMMON/TO_MIRROR/IMIRROR, IPROC
C     ----------
C     BEGIN CODE
C     ----------
      P1_DSIG=0D0


C     Select among the subprocesses based on PDF weight
      DO IPROC=1,MAXSPROC
        DO IMIRROR=1,2
          IF(IMIRROR.EQ.1.OR.MIRRORPROCS(IPROC))THEN
            P1_DSIG=P1_DSIG+P1_DSIGPROC(PP,IPROC,IMIRROR)
            IF(IMIRROR.EQ.2)THEN
C             Need to flip back x values
              XDUM=XBK(1)
              XBK(1)=XBK(2)
              XBK(2)=XDUM
            ENDIF
          ENDIF
        ENDDO
      ENDDO


      RETURN
      END

      FUNCTION P1_DSIGPROC(PP,IPROC,IMIRROR)
C     ****************************************************
C     RETURNS DIFFERENTIAL CROSS SECTION 
C     FOR A PROCESS
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     Output:
C     Amplitude squared and summed
C     ****************************************************

      IMPLICIT NONE

      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION P1_DSIGPROC
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
      INTEGER IPROC,IMIRROR
C     
C     GLOBAL VARIABLES
C     
C     SUBDIAG is vector of diagram numbers for this config
C     IB gives which beam is which (for mirror processes)
      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
C     
C     EXTERNAL FUNCTIONS
C     
      DOUBLE PRECISION P1_DSIG1,P1_DSIG2,P1_DSIG3,P1_DSIG4,P1_DSIG5,P1_DSIG6,P1_DSIG7,P1_DSIG8
     $ ,P1_DSIG9,P1_DSIG10,P1_DSIG11,P1_DSIG12,P1_DSIG13,P1_DSIG14,P1_DSIG15,P1_DSIG16,P1_DSIG17
     $ ,P1_DSIG18,P1_DSIG19,P1_DSIG20,P1_DSIG21,P1_DSIG22,P1_DSIG23,P1_DSIG24,P1_DSIG25,P1_DSIG26
     $ ,P1_DSIG27,P1_DSIG28,P1_DSIG29,P1_DSIG30,P1_DSIG31,P1_DSIG32,P1_DSIG33,P1_DSIG34,P1_DSIG35
     $ ,P1_DSIG36,P1_DSIG37,P1_DSIG38,P1_DSIG39,P1_DSIG40,P1_DSIG41,P1_DSIG42,P1_DSIG43,P1_DSIG44
     $ ,P1_DSIG45,P1_DSIG46,P1_DSIG47,P1_DSIG48,P1_DSIG49,P1_DSIG50,P1_DSIG51,P1_DSIG52,P1_DSIG53
     $ ,P1_DSIG54,P1_DSIG55,P1_DSIG56,P1_DSIG57,P1_DSIG58,P1_DSIG59,P1_DSIG60,P1_DSIG61,P1_DSIG62
     $ ,P1_DSIG63,P1_DSIG64,P1_DSIG65,P1_DSIG66,P1_DSIG67,P1_DSIG68,P1_DSIG69,P1_DSIG70,P1_DSIG71
     $ ,P1_DSIG72,P1_DSIG73,P1_DSIG74,P1_DSIG75,P1_DSIG76,P1_DSIG77,P1_DSIG78,P1_DSIG79,P1_DSIG80
     $ ,P1_DSIG81,P1_DSIG82,P1_DSIG83,P1_DSIG84,P1_DSIG85,P1_DSIG86,P1_DSIG87,P1_DSIG88,P1_DSIG89
     $ ,P1_DSIG90,P1_DSIG91,P1_DSIG92,P1_DSIG93,P1_DSIG94,P1_DSIG95,P1_DSIG96,P1_DSIG97,P1_DSIG98
     $ ,P1_DSIG99,P1_DSIG100,P1_DSIG101,P1_DSIG102,P1_DSIG103,P1_DSIG104
      LOGICAL PASSCUTS
C     
C     LOCAL VARIABLES 
C     
      DOUBLE PRECISION P1(0:3,NEXTERNAL),XDUM
      DOUBLE PRECISION PTEMP(0:3)
      INTEGER I,J,K
      INTEGER IMODE

      IMODE=1  ! DUMMY VARIABLE
      DO I=1,NEXTERNAL
        DO J=0,3
          P1(J,I)=PP(J,I)
        ENDDO
      ENDDO

      IB(1)=1
      IB(2)=2

      IF(IMIRROR.EQ.2)THEN
        DO I=0,3
          PTEMP(I)=P1(I,1)
          P1(I,1)=P1(I,2)
          P1(I,2)=PTEMP(I)
        ENDDO
C       Flip x values 
        XDUM=XBK(1)
        XBK(1)=XBK(2)
        XBK(2)=XDUM
      ENDIF

      P1_DSIGPROC=0D0

      IF(IPROC.EQ.1) P1_DSIGPROC=P1_DSIG1(P1,WGT,IMODE)  ! g g > e- ve~ g g u d~
      IF(IPROC.EQ.2) P1_DSIGPROC=P1_DSIG2(P1,WGT,IMODE)  ! g g > e- ve~ u u u~ d~
      IF(IPROC.EQ.3) P1_DSIGPROC=P1_DSIG3(P1,WGT,IMODE)  ! g g > e- ve~ u c u~ s~
      IF(IPROC.EQ.4) P1_DSIGPROC=P1_DSIG4(P1,WGT,IMODE)  ! g g > e- ve~ u d d~ d~
      IF(IPROC.EQ.5) P1_DSIGPROC=P1_DSIG5(P1,WGT,IMODE)  ! g u > e- ve~ g u u d~
      IF(IPROC.EQ.6) P1_DSIGPROC=P1_DSIG6(P1,WGT,IMODE)  ! g u > e- ve~ g u c s~
      IF(IPROC.EQ.7) P1_DSIGPROC=P1_DSIG7(P1,WGT,IMODE)  ! g d > e- ve~ g g g u
      IF(IPROC.EQ.8) P1_DSIGPROC=P1_DSIG8(P1,WGT,IMODE)  ! g d > e- ve~ g u u u~
      IF(IPROC.EQ.9) P1_DSIGPROC=P1_DSIG9(P1,WGT,IMODE)  ! g d > e- ve~ g u c c~
      IF(IPROC.EQ.10) P1_DSIGPROC=P1_DSIG10(P1,WGT,IMODE)  ! g d > e- ve~ g u d d~
      IF(IPROC.EQ.11) P1_DSIGPROC=P1_DSIG11(P1,WGT,IMODE)  ! g u~ > e- ve~ g g g d~
      IF(IPROC.EQ.12) P1_DSIGPROC=P1_DSIG12(P1,WGT,IMODE)  ! g u~ > e- ve~ g u u~ d~
      IF(IPROC.EQ.13) P1_DSIGPROC=P1_DSIG13(P1,WGT,IMODE)  ! g u~ > e- ve~ g c u~ s~
      IF(IPROC.EQ.14) P1_DSIGPROC=P1_DSIG14(P1,WGT,IMODE)  ! g u~ > e- ve~ g c c~ d~
      IF(IPROC.EQ.15) P1_DSIGPROC=P1_DSIG15(P1,WGT,IMODE)  ! g u~ > e- ve~ g d d~ d~
      IF(IPROC.EQ.16) P1_DSIGPROC=P1_DSIG16(P1,WGT,IMODE)  ! g d~ > e- ve~ g u d~ d~
      IF(IPROC.EQ.17) P1_DSIGPROC=P1_DSIG17(P1,WGT,IMODE)  ! u u > e- ve~ u u u d~
      IF(IPROC.EQ.18) P1_DSIGPROC=P1_DSIG18(P1,WGT,IMODE)  ! u u > e- ve~ u u c s~
      IF(IPROC.EQ.19) P1_DSIGPROC=P1_DSIG19(P1,WGT,IMODE)  ! u c > e- ve~ u u c d~
      IF(IPROC.EQ.20) P1_DSIGPROC=P1_DSIG20(P1,WGT,IMODE)  ! u c > e- ve~ u c c s~
      IF(IPROC.EQ.21) P1_DSIGPROC=P1_DSIG21(P1,WGT,IMODE)  ! u d > e- ve~ g g u u
      IF(IPROC.EQ.22) P1_DSIGPROC=P1_DSIG22(P1,WGT,IMODE)  ! u d > e- ve~ u u u u~
      IF(IPROC.EQ.23) P1_DSIGPROC=P1_DSIG23(P1,WGT,IMODE)  ! u d > e- ve~ u u c c~
      IF(IPROC.EQ.24) P1_DSIGPROC=P1_DSIG24(P1,WGT,IMODE)  ! u d > e- ve~ u u d d~
      IF(IPROC.EQ.25) P1_DSIGPROC=P1_DSIG25(P1,WGT,IMODE)  ! u d > e- ve~ u c d s~
      IF(IPROC.EQ.26) P1_DSIGPROC=P1_DSIG26(P1,WGT,IMODE)  ! u s > e- ve~ g g u c
      IF(IPROC.EQ.27) P1_DSIGPROC=P1_DSIG27(P1,WGT,IMODE)  ! u s > e- ve~ u u c u~
      IF(IPROC.EQ.28) P1_DSIGPROC=P1_DSIG28(P1,WGT,IMODE)  ! u s > e- ve~ u c c c~
      IF(IPROC.EQ.29) P1_DSIGPROC=P1_DSIG29(P1,WGT,IMODE)  ! u s > e- ve~ u c d d~
      IF(IPROC.EQ.30) P1_DSIGPROC=P1_DSIG30(P1,WGT,IMODE)  ! u s > e- ve~ u c s s~
      IF(IPROC.EQ.31) P1_DSIGPROC=P1_DSIG31(P1,WGT,IMODE)  ! u u~ > e- ve~ g g u d~
      IF(IPROC.EQ.32) P1_DSIGPROC=P1_DSIG32(P1,WGT,IMODE)  ! u u~ > e- ve~ g g c s~
      IF(IPROC.EQ.33) P1_DSIGPROC=P1_DSIG33(P1,WGT,IMODE)  ! u u~ > e- ve~ u u u~ d~
      IF(IPROC.EQ.34) P1_DSIGPROC=P1_DSIG34(P1,WGT,IMODE)  ! u u~ > e- ve~ u c u~ s~
      IF(IPROC.EQ.35) P1_DSIGPROC=P1_DSIG35(P1,WGT,IMODE)  ! u u~ > e- ve~ u c c~ d~
      IF(IPROC.EQ.36) P1_DSIGPROC=P1_DSIG36(P1,WGT,IMODE)  ! u u~ > e- ve~ u d d~ d~
      IF(IPROC.EQ.37) P1_DSIGPROC=P1_DSIG37(P1,WGT,IMODE)  ! u u~ > e- ve~ c c c~ s~
      IF(IPROC.EQ.38) P1_DSIGPROC=P1_DSIG38(P1,WGT,IMODE)  ! u u~ > e- ve~ c d d~ s~
      IF(IPROC.EQ.39) P1_DSIGPROC=P1_DSIG39(P1,WGT,IMODE)  ! u u~ > e- ve~ c s s~ s~
      IF(IPROC.EQ.40) P1_DSIGPROC=P1_DSIG40(P1,WGT,IMODE)  ! u c~ > e- ve~ g g u s~
      IF(IPROC.EQ.41) P1_DSIGPROC=P1_DSIG41(P1,WGT,IMODE)  ! u c~ > e- ve~ u u u~ s~
      IF(IPROC.EQ.42) P1_DSIGPROC=P1_DSIG42(P1,WGT,IMODE)  ! u c~ > e- ve~ u u c~ d~
      IF(IPROC.EQ.43) P1_DSIGPROC=P1_DSIG43(P1,WGT,IMODE)  ! u c~ > e- ve~ u c c~ s~
      IF(IPROC.EQ.44) P1_DSIGPROC=P1_DSIG44(P1,WGT,IMODE)  ! u c~ > e- ve~ u d d~ s~
      IF(IPROC.EQ.45) P1_DSIGPROC=P1_DSIG45(P1,WGT,IMODE)  ! u c~ > e- ve~ u s s~ s~
      IF(IPROC.EQ.46) P1_DSIGPROC=P1_DSIG46(P1,WGT,IMODE)  ! u d~ > e- ve~ u u d~ d~
      IF(IPROC.EQ.47) P1_DSIGPROC=P1_DSIG47(P1,WGT,IMODE)  ! u d~ > e- ve~ u c d~ s~
      IF(IPROC.EQ.48) P1_DSIGPROC=P1_DSIG48(P1,WGT,IMODE)  ! u s~ > e- ve~ u c s~ s~
      IF(IPROC.EQ.49) P1_DSIGPROC=P1_DSIG49(P1,WGT,IMODE)  ! d d > e- ve~ g g u d
      IF(IPROC.EQ.50) P1_DSIGPROC=P1_DSIG50(P1,WGT,IMODE)  ! d d > e- ve~ u u d u~
      IF(IPROC.EQ.51) P1_DSIGPROC=P1_DSIG51(P1,WGT,IMODE)  ! d d > e- ve~ u c d c~
      IF(IPROC.EQ.52) P1_DSIGPROC=P1_DSIG52(P1,WGT,IMODE)  ! d d > e- ve~ u d d d~
      IF(IPROC.EQ.53) P1_DSIGPROC=P1_DSIG53(P1,WGT,IMODE)  ! d s > e- ve~ g g u s
      IF(IPROC.EQ.54) P1_DSIGPROC=P1_DSIG54(P1,WGT,IMODE)  ! d s > e- ve~ u u s u~
      IF(IPROC.EQ.55) P1_DSIGPROC=P1_DSIG55(P1,WGT,IMODE)  ! d s > e- ve~ u c s c~
      IF(IPROC.EQ.56) P1_DSIGPROC=P1_DSIG56(P1,WGT,IMODE)  ! d s > e- ve~ u d s d~
      IF(IPROC.EQ.57) P1_DSIGPROC=P1_DSIG57(P1,WGT,IMODE)  ! d s > e- ve~ u s s s~
      IF(IPROC.EQ.58) P1_DSIGPROC=P1_DSIG58(P1,WGT,IMODE)  ! d u~ > e- ve~ g g g g
      IF(IPROC.EQ.59) P1_DSIGPROC=P1_DSIG59(P1,WGT,IMODE)  ! d u~ > e- ve~ g g u u~
      IF(IPROC.EQ.60) P1_DSIGPROC=P1_DSIG60(P1,WGT,IMODE)  ! d u~ > e- ve~ g g c c~
      IF(IPROC.EQ.61) P1_DSIGPROC=P1_DSIG61(P1,WGT,IMODE)  ! d u~ > e- ve~ g g d d~
      IF(IPROC.EQ.62) P1_DSIGPROC=P1_DSIG62(P1,WGT,IMODE)  ! d u~ > e- ve~ u u u~ u~
      IF(IPROC.EQ.63) P1_DSIGPROC=P1_DSIG63(P1,WGT,IMODE)  ! d u~ > e- ve~ u c u~ c~
      IF(IPROC.EQ.64) P1_DSIGPROC=P1_DSIG64(P1,WGT,IMODE)  ! d u~ > e- ve~ u d u~ d~
      IF(IPROC.EQ.65) P1_DSIGPROC=P1_DSIG65(P1,WGT,IMODE)  ! d u~ > e- ve~ u s u~ s~
      IF(IPROC.EQ.66) P1_DSIGPROC=P1_DSIG66(P1,WGT,IMODE)  ! d u~ > e- ve~ c c c~ c~
      IF(IPROC.EQ.67) P1_DSIGPROC=P1_DSIG67(P1,WGT,IMODE)  ! d u~ > e- ve~ c d c~ d~
      IF(IPROC.EQ.68) P1_DSIGPROC=P1_DSIG68(P1,WGT,IMODE)  ! d u~ > e- ve~ c s c~ s~
      IF(IPROC.EQ.69) P1_DSIGPROC=P1_DSIG69(P1,WGT,IMODE)  ! d u~ > e- ve~ d d d~ d~
      IF(IPROC.EQ.70) P1_DSIGPROC=P1_DSIG70(P1,WGT,IMODE)  ! d u~ > e- ve~ d s d~ s~
      IF(IPROC.EQ.71) P1_DSIGPROC=P1_DSIG71(P1,WGT,IMODE)  ! d c~ > e- ve~ g g u c~
      IF(IPROC.EQ.72) P1_DSIGPROC=P1_DSIG72(P1,WGT,IMODE)  ! d c~ > e- ve~ u u u~ c~
      IF(IPROC.EQ.73) P1_DSIGPROC=P1_DSIG73(P1,WGT,IMODE)  ! d c~ > e- ve~ u c c~ c~
      IF(IPROC.EQ.74) P1_DSIGPROC=P1_DSIG74(P1,WGT,IMODE)  ! d c~ > e- ve~ u d c~ d~
      IF(IPROC.EQ.75) P1_DSIGPROC=P1_DSIG75(P1,WGT,IMODE)  ! d c~ > e- ve~ u s c~ s~
      IF(IPROC.EQ.76) P1_DSIGPROC=P1_DSIG76(P1,WGT,IMODE)  ! d d~ > e- ve~ g g u d~
      IF(IPROC.EQ.77) P1_DSIGPROC=P1_DSIG77(P1,WGT,IMODE)  ! d d~ > e- ve~ u u u~ d~
      IF(IPROC.EQ.78) P1_DSIGPROC=P1_DSIG78(P1,WGT,IMODE)  ! d d~ > e- ve~ u c c~ d~
      IF(IPROC.EQ.79) P1_DSIGPROC=P1_DSIG79(P1,WGT,IMODE)  ! d d~ > e- ve~ u d d~ d~
      IF(IPROC.EQ.80) P1_DSIGPROC=P1_DSIG80(P1,WGT,IMODE)  ! s c~ > e- ve~ u c u~ c~
      IF(IPROC.EQ.81) P1_DSIGPROC=P1_DSIG81(P1,WGT,IMODE)  ! s c~ > e- ve~ u d u~ d~
      IF(IPROC.EQ.82) P1_DSIGPROC=P1_DSIG82(P1,WGT,IMODE)  ! u~ u~ > e- ve~ g g u~ d~
      IF(IPROC.EQ.83) P1_DSIGPROC=P1_DSIG83(P1,WGT,IMODE)  ! u~ u~ > e- ve~ u u~ u~ d~
      IF(IPROC.EQ.84) P1_DSIGPROC=P1_DSIG84(P1,WGT,IMODE)  ! u~ u~ > e- ve~ c u~ u~ s~
      IF(IPROC.EQ.85) P1_DSIGPROC=P1_DSIG85(P1,WGT,IMODE)  ! u~ u~ > e- ve~ c u~ c~ d~
      IF(IPROC.EQ.86) P1_DSIGPROC=P1_DSIG86(P1,WGT,IMODE)  ! u~ u~ > e- ve~ d u~ d~ d~
      IF(IPROC.EQ.87) P1_DSIGPROC=P1_DSIG87(P1,WGT,IMODE)  ! u~ c~ > e- ve~ g g u~ s~
      IF(IPROC.EQ.88) P1_DSIGPROC=P1_DSIG88(P1,WGT,IMODE)  ! u~ c~ > e- ve~ g g c~ d~
      IF(IPROC.EQ.89) P1_DSIGPROC=P1_DSIG89(P1,WGT,IMODE)  ! u~ c~ > e- ve~ u u~ u~ s~
      IF(IPROC.EQ.90) P1_DSIGPROC=P1_DSIG90(P1,WGT,IMODE)  ! u~ c~ > e- ve~ u u~ c~ d~
      IF(IPROC.EQ.91) P1_DSIGPROC=P1_DSIG91(P1,WGT,IMODE)  ! u~ c~ > e- ve~ c u~ c~ s~
      IF(IPROC.EQ.92) P1_DSIGPROC=P1_DSIG92(P1,WGT,IMODE)  ! u~ c~ > e- ve~ c c~ c~ d~
      IF(IPROC.EQ.93) P1_DSIGPROC=P1_DSIG93(P1,WGT,IMODE)  ! u~ c~ > e- ve~ d u~ d~ s~
      IF(IPROC.EQ.94) P1_DSIGPROC=P1_DSIG94(P1,WGT,IMODE)  ! u~ c~ > e- ve~ d c~ d~ d~
      IF(IPROC.EQ.95) P1_DSIGPROC=P1_DSIG95(P1,WGT,IMODE)  ! u~ c~ > e- ve~ s u~ s~ s~
      IF(IPROC.EQ.96) P1_DSIGPROC=P1_DSIG96(P1,WGT,IMODE)  ! u~ c~ > e- ve~ s c~ d~ s~
      IF(IPROC.EQ.97) P1_DSIGPROC=P1_DSIG97(P1,WGT,IMODE)  ! u~ d~ > e- ve~ g g d~ d~
      IF(IPROC.EQ.98) P1_DSIGPROC=P1_DSIG98(P1,WGT,IMODE)  ! u~ d~ > e- ve~ u u~ d~ d~
      IF(IPROC.EQ.99) P1_DSIGPROC=P1_DSIG99(P1,WGT,IMODE)  ! u~ d~ > e- ve~ c u~ d~ s~
      IF(IPROC.EQ.100) P1_DSIGPROC=P1_DSIG100(P1,WGT,IMODE)  ! u~ d~ > e- ve~ c c~ d~ d~
      IF(IPROC.EQ.101) P1_DSIGPROC=P1_DSIG101(P1,WGT,IMODE)  ! u~ d~ > e- ve~ d d~ d~ d~
      IF(IPROC.EQ.102) P1_DSIGPROC=P1_DSIG102(P1,WGT,IMODE)  ! u~ s~ > e- ve~ c u~ s~ s~
      IF(IPROC.EQ.103) P1_DSIGPROC=P1_DSIG103(P1,WGT,IMODE)  ! d~ d~ > e- ve~ u d~ d~ d~
      IF(IPROC.EQ.104) P1_DSIGPROC=P1_DSIG104(P1,WGT,IMODE)  ! d~ s~ > e- ve~ u d~ d~ s~
      RETURN
      END


